services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: postgres
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    command: python djproject/manage.py runserver 0.0.0.0:8000
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./backend:/code
    container_name: django
    ports:
      - '8000:8000'
    depends_on:
      - db

volumes:
  postgres_data: